routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

//Route::get('/', 'IndexController')->name('index');

//Route::get('/welcome', 'WelcomeController')->name('welcome');
Route::get('/', 'WelcomeController')->name('welcome');

Route::group([
    'namespace' => 'Registration',
    'prefix'    => 'Registration',
    'as'        => 'registration.',
], function () {
    Route::resource('companies', 'CompanyController');
    Route::resource('certificates', 'CertificateController');
    Route::resource('owners', 'OwnerController');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'namespace' => 'User',
    'prefix'    => 'user',
    'as'        => 'user.',
], function () {
    Route::get('/', 'UserController@show')->name('show');
    Route::put('/', 'UserController@update')->name('update');
    Route::get('/password', 'PasswordController@show')->name('password.show');
    Route::put('/password', 'PasswordController@update')->name('password.update');
    Route::get('/logs', 'LogController')->name('logs');
    Route::get('/avatar', 'AvatarController@show')->name('avatar.show');
    Route::post('/avatar', 'AvatarController@store')->name('avatar.store');
});

Route::resource('/sale', 'SaleController');
Route::resource('/reports', 'ReportController');
Route::resource('/reporting', 'ReportingController');
Route::resource('/configurations', 'ConfigurationController');

Route::get('/language/{language}', 'LanguageController')->name('language');

Route::group([
    'namespace' => 'Manage',
    'prefix'    => 'manage',
    'as'        => 'manage.',
], function () {
    Route::resource('users', 'UserController')->except('store', 'update', 'destroy');
    Route::resource('companies', 'CompanyController');
    Route::resource('owners', 'OwnerController');
    Route::resource('certificates', 'CertificateController');
    Route::post('certificates/storeCIDB', 'CertificateController@storeCIDB');
    Route::resource('document_acceptances', 'DocumentAcceptanceController');
    Route::get('/document_acceptances/{document_acceptances}/list', 'DocumentAcceptanceController@list')->name('document_acceptances.list');
    Route::get('/document_acceptances/{document_acceptances}/shows', 'DocumentAcceptanceController@shows')->name('document_acceptances.shows');
    Route::get('/document_acceptances/{document_acceptances}/edits', 'DocumentAcceptanceController@edits')->name('document_acceptances.edits');

    Route::group([
        'namespace' => 'Committee',
        'prefix'    => 'committee',
        'as'        => 'committee.',
    ], function () {
        Route::resource('assessments', 'AssessmentController');
        Route::resource('approvals', 'ApprovalController');
    });
});
Route::group([
        'namespace' => 'Contract\Acquisition\Document',
        'prefix'    => 'doc',
        'as'        => 'doc.',
    ], function () {
        Route::resource('addenda', 'AddendaController');
    });

Route::group([
        'namespace' => 'Contract\Acquisition',
        'prefix'    => 'acq',
        'as'        => 'acq.',
    ], function () {
        Route::resource('document', 'DocumentController');
        Route::resource('acquisition', 'AcquisitionController');
        Route::resource('review', 'ReviewController');
        Route::resource('lawreview', 'LawReviewController');
    });

Route::group([
    'namespace' => 'Contract',
    'prefix'    => 'contract',
    'as'        => 'contract.',
], function () {
    Route::resource('pre', 'PreController');
    Route::resource('post', 'PostController');
});
Route::resource('/import', 'ImportController');

Route::group([
    'namespace' => 'Contract\Post',
    'prefix'    => 'extension',
    'as'        => 'extension.',
], function () {
    Route::resource('extension', 'ExtensionController');
});

app/Http/Controllers/Api/Contract/Acquisition/Monitoring/ContractProgressController.php
<?php

namespace App\Http\Controllers\Api\Contract\Acquisition\Monitoring;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContractProgressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            //'site_visit_percent'  => 'required',
            //'on_site_payment_percent' => 'required'
        ]);

//        $data = $request->only(
//            'id',
//            'site_visit_percent'
//        );
               
         //add update contract progress
        $id_contract_progress = $request->id;
        $contractProgressObj = \App\Models\Acquisition\Monitoring\ContractProgress::find($id_contract_progress);
               // ->update(['deleted' => 1]);
             
        
        //update site visit
        
            
         if(!is_null($contractProgressObj->site_visit_id))  { 
            $siteVisitObj = \App\Models\Acquisition\Monitoring\SiteVisit::find($contractProgressObj->site_visit_id);
            if(!is_null($siteVisitObj)){
               $siteVisitObj->update(['percentage_completed' => $request->site_visit_percent]);
            }
         }
         
         //update onsite payment
//         if(!is_null($contractProgressObj->payment_monitor_id))  { 
//            $onSitePaymentObj = \App\Models\Acquisition\Monitoring\PaymentMonitor::find($contractProgressObj->payment_monitor_id);
//            if(!is_null($onSitePaymentObj)){
//               $onSitePaymentObj->update(['payment_percent' => $request->on_site_payment_percent]);
//            }
//         }
     
         
        $contractProgressObj->update(['on_site_payment_percent' => $request->on_site_payment_percent]);      
        return response()->api(null, __('Rekod telah berjaya dikemaskini.'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contractProgress = \App\Models\Acquisition\Monitoring\ContractProgress::find($id);
        $siteVisit = \App\Models\Acquisition\Monitoring\SiteVisit::find($contractProgress->site_visit_id);
        
        //return response()->json
        return response()->json(['contractProgress'=>$contractProgress,'siteVisit'=>$siteVisit]);
        //return \App\Models\Acquisition\Monitoring\ContractProgress::find($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //TODO -change : \App\Models\Acquisition\Monitoring\SiteVisit::hashslug($id)->delete();

        return response()->api(null, __('Rekod telah berjaya dihapuskan.'));
    }
}

app/Http/Controllers/Api/Contract/Acquisition/Monitoring/PaymentMonitorController.php
<?php

namespace App\Http\Controllers\Api\Contract\Acquisition\Monitoring;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PaymentMonitorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $this->validate($request, [
//            'user_id'                 => 'required',
//            'sst_id'                  => 'required',
//            'department_id'           => 'required',
//            'acquisition_id'          => 'required',
//            'acquisition_approval_id' => 'required',
//            'name'                    => 'required|min:10|max:255',
//            'remarks'                 => 'required|min:10|max:255',
//            'visited_by'              => 'required',
//        ]);

        $data = $request->only(
 //           'user_id',
 //           'sst_id',
 //           'department_id',
            'acquisition_id',
 //           'acquisition_approval_id',
 //           'payment_at',
            'payment_percent'
  //          'visited_by',
  //          'percentage_completed'
        );
        
        
         //add update contract progress
        $id_contract_progress = $request->id_contract_progress;
        $contractProgressObj = \App\Models\Acquisition\Monitoring\ContractProgress::find($id_contract_progress);
               // ->update(['deleted' => 1]);
        
        //$data['visited_at'] = now();
        $data['payment_at'] = $contractProgressObj->on_plan_date;
        
        
        //$site_visit = \App\Models\Acquisition\Monitoring\SiteVisit::create($data);
        $payment_monitor = \App\Models\Acquisition\Monitoring\PaymentMonitor::create($data);
        
        
        //$site_visit->addDocument($request, 'document');
        
       
        $contractProgressObj->update(['payment_monitor_id' => $payment_monitor->id]);
        
        
        

        return response()->api(null, __('Rekod telah berjaya ditambah.'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //TODO -change : \App\Models\Acquisition\Monitoring\SiteVisit::hashslug($id)->delete();

        return response()->api(null, __('Rekod telah berjaya dihapuskan.'));
    }
}

app/Http/Controllers/Api/Contract/Acquisition/Monitoring/SiteVisitController.php
<?php

namespace App\Http\Controllers\Api\Contract\Acquisition\Monitoring;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\WorkflowTask;

use Carbon\Carbon;

class SiteVisitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'user_id'                 => 'required',
            'sst_id'                  => 'required',
            'department_id'           => 'required',
            'acquisition_id'          => 'required',
            'acquisition_approval_id' => 'required',
            'name'                    => 'required|max:255',
            'remarks'                 => 'required|max:255',
            'visited_by'              => 'required',
            'visit_date'          => 'required',
            'percentage_completed' => 'required',
        ]);

        $data = $request->only(
            'user_id',
            'sst_id',
            'department_id',
            'acquisition_id',
            'acquisition_approval_id',
            'name',
            'remarks',
            'visited_by',
            'percentage_completed'
            //,'visit_date'
        );
        
        
         //add update contract progress
        $id_contract_progress = $request->id_contract_progress;
        $contractProgressObj = \App\Models\Acquisition\Monitoring\ContractProgress::find($id_contract_progress);
               // ->update(['deleted' => 1]);
        
        //$data['visited_at'] = now();
        $data['visited_at'] = $contractProgressObj->on_plan_date;
        $data['visit_date'] =  Carbon::createFromFormat('d/m/Y', $request->visit_date);
        
        $site_visit = \App\Models\Acquisition\Monitoring\SiteVisit::create($data);

        $site_visit->addDocument($request, 'document');
        
       
        $contractProgressObj->update(['site_visit_id' => $site_visit->id]);
        
        $workflow = WorkflowTask::where('acquisition_id',$request->acquisition_id)->where('workflow_team_id',1)->first();
        $workflow->flow_desc = '';
        $workflow->flow_location = 'Pemantauan Projek';
        $workflow->url = '';
        $workflow->user_id = null;
        $workflow->update();
        
        return response()->api(null, __('Rekod telah berjaya ditambah.'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $siteVisit = \App\Models\Acquisition\Monitoring\SiteVisit::findByHashSlug($id);
        $view_visit_by = $siteVisit->visitedBy->name;
        
        $visit_date_view = $siteVisit->visit_date->format('d/m/Y');
        $visited_at_view = $siteVisit->visited_at->format('d/m/Y');
        
        return response()->json(['siteVisit'=>$siteVisit , 'view_visit_by'=>$view_visit_by,
            'visit_date_view'=>$visit_date_view,
            'visited_at_view'=>$visited_at_view
            ]);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Models\Acquisition\Monitoring\SiteVisit::hashslug($id)->delete();

        return response()->api(null, __('Rekod telah berjaya dihapuskan.'));
    }
    
    
    //Cetak Lawatan Tapak
    
    
    
}

app/Http/Controllers/Api/Contract/Acquisition/MonitoringController.php
<?php

namespace App\Http\Controllers\Api\Contract\Acquisition;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MonitoringController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }
}

app/Http/Controllers/Api/Datatable/Contract/Acquisition/Monitoring/ContractProgressController.php
<?php

namespace App\Http\Controllers\Api\Datatable\Contract\Acquisition\Monitoring;

use App\Http\Controllers\Controller;
use App\Models\Acquisition\Monitoring\ContractProgress;
use App\Transformers\Datatable\ContractProgressTransformer as Transformer;
use Illuminate\Http\Request;

class ContractProgressController extends Controller
{
    public function __invoke(Request $request)
    {
//        $dummyAcquisitionId = 1;     
//        $list  = ContractProgress::
//                where('acquisition_id', $dummyAcquisitionId)->datatable();
//
//        return app('datatables')
//            ->eloquent($list)
//            ->setTransformer(new Transformer())
//            ->toJson();
    }
}

app/Http/Controllers/Api/Datatable/Contract/Acquisition/Monitoring/PaymentMonitorController.php
<?php

namespace App\Http\Controllers\Api\Datatable\Contract\Acquisition\Monitoring;

use App\Http\Controllers\Controller;
use App\Models\Acquisition\Monitoring\PaymentMonitor;
use App\Transformers\Datatable\PaymentMonitorTransformer as Transformer;
use Illuminate\Http\Request;
use App\Models\Acquisition\Sst;

class PaymentMonitorController extends Controller
{
    public function __invoke(Request $request)
    {
        $hashslug = $request->get('hashslug');

        //find by acquisition id , this id need get from hashlug of        
        //find SST by hashlug
        $sst = Sst::where('hashslug', $hashslug)->first();
        
        $query = PaymentMonitor::
                where('acquisition_id', $sst->acquisition_id)->datatable();

        return app('datatables')
            ->eloquent($query)
            ->setTransformer(new Transformer())
            ->toJson();
    }
}

resources/views/contract/post/monitoring/index.blade.php
@extends('layouts.admin')

@push('scripts')
    @include('components.charts.utils')
     <script src="{{asset('js/hideShowPassword.min.js')}}"></script>
@endpush

  @push('scripts')
    <script type="text/javascript">
        jQuery(document).ready(function($) {
           @foreach(chart()->monitoring() as $key => $chart)
                @if(!empty($chart))
                    createChart(@json($chart), '{{ snake_case($key) }}');
                @endif
           @endforeach
           
           
            $('#est_cost_project').hidePassword(true);
           
        });
    </script>
   
@endpush

@section('content')




<div class="row">
<!--    @forelse(dashboard()->monitoring() as $item)
        <div class="col-6">
            @component('components.cards.figure')
                @slot('content')
                    {{ $item['content'] }}
                @endslot
                @slot('footer')
                    {{ $item['footer'] }}
                    @if(!empty($item['data']))
                        <div class="m-3 text-left">
                            @foreach($item['data'] as $label => $url)
                                <a target="_blank" class="tag tag-primary m-1" href="{{ $url }}">{{ $label }}</a>
                            @endforeach
                        </div>
                    @endif
                @endslot
            @endcomponent
        </div>
    @empty
        <div class="col">
            @include('components.cards.empty-info', ['header' => 'Maklumat Pemantauan Projek'])
        </div>
    @endforelse-->

<div class="col-6">
@component('components.cards.figure')
    @slot('content')
     {{$contractsNotAwardYet}}
    @endslot
    @slot('footer') 
    <a class="tag tag-primary m-1" href="{{ route('acquisition.acquisition.index') }}?tag=contractsNotAwardYet">
      Perolehan Belum Di Award Lagi
      </a>
       <div class="m-3 text-left">                         
<!-- if want link one by one 
<a target="_blank" class="tag tag-primary m-1" href="http://google.com">109</a>-->
      </div>
    @endslot
   @endcomponent
 </div>

<div class="col-6">
@component('components.cards.figure')
    @slot('content')
     {{$contractsNotSignedYet}}
    @endslot
    @slot('footer')
    <a class="tag tag-primary m-1" href="{{ route('acceptance-letter.index') }}?tag=contractsNotSignedYet">
        Kontrak Belum Di Tandatangan
    </a>
       <div class="m-3 text-left">                         
<!-- if want link one by one 
<a target="_blank" class="tag tag-primary m-1" href="http://google.com">109</a>-->
      </div>
    @endslot
   @endcomponent
 </div>

 <div class="col-6">
@component('components.cards.figure')
    @slot('content')
     {{$contractsOnGoing}}
    @endslot
    @slot('footer')
    <a class="tag tag-primary m-1" href="{{ route('acceptance-letter.index') }}?tag=ContractOnGoing">Kontrak Sedang Berjalan</a>
<!--      Kontrak Sedang Berjalan-->
       <div class="m-3 text-left">                         
<!-- if want link one by one 
<a target="_blank" class="tag tag-primary m-1" href="http://google.com">109</a>-->
      </div>
    @endslot
   @endcomponent
 </div>

<div class="col-6">
@component('components.cards.figure')
    @slot('content')
     {{$contractsDoneButNotSofaYet}}
    @endslot
    @slot('footer')
    <a class="tag tag-primary m-1" href="{{ route('acceptance-letter.index') }}?tag=contractsDoneButNotSofaYet">
        Kerja Telah Siap Tetapi Belum Di SOFA 
    </a>
      
       <div class="m-3 text-left">                         
<!-- if want link one by one 
<a target="_blank" class="tag tag-primary m-1" href="http://google.com">109</a>-->
      </div>
    @endslot
   @endcomponent
 </div>
   
   

 <div class="col-6">
@component('components.cards.figure')
    @slot('content')
     {{$contractsSixMonthToEnd}}
    @endslot
    @slot('footer')
      <a  class="tag tag-primary m-1" href="{{ route('acceptance-letter.index') }}?tag=6MonthToEnd">
          Kontrak akan Tamat dalam Tempoh 6 Bulan</a>
       <div class="m-3 text-left">                         
<!-- if want link one by one 
<a target="_blank" class="tag tag-primary m-1" href="http://google.com">109</a>-->
      </div>
    @endslot
   @endcomponent
 </div>



 
   

 

 
   
   
 

</div>
   



    <div class="row justify-content-center">
        <div class="col">
            @include('contract.post.monitoring.partials.scripts')
            @component('components.card')
                @slot('card_body')
                    @component('components.datatable', 
                        [
                            'table_id' => 'contract-post-monitoring',
                            'route_name' => 'api.datatable.contract.acquisition.monitoring',
                            'columns' => [
                                ['data' => 'no_kontrak', 'title' => __('No. Kontrak'), 'defaultContent' => '-'],
                                ['data' => 'tajuk', 'title' => __('Tajuk'), 'defaultContent' => '-'],
                                ['data' => 'syarikat_terpilih', 'title' => __('Syarikat Terpilih'), 'defaultContent' => '-'],
                                ['data' => null , 'name' => null, 'searchable' => false, 'orderable' => false],
                            ],
                            'headers' => [
                                __('No. Kontrak'), __('Tajuk'), __('Syarikat Terpilih'), __('table.action')
                            ],
                            'actions' => minify(view('contract.post.monitoring.partials.actions')->render())
                        ]
                    )
                    @endcomponent
                @endslot
            @endcomponent
        </div>
    </div>
@endsection